######################################################################
# Automatically generated by qmake (2.01a) Fr. Jul 8 12:16:07 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += staticlib

# Input
HEADERS += RandomGenerator.h \
    math_constants.h
SOURCES += RandomGenerator.cpp \
    math_constants.cpp
