######################################################################
# Automatically generated by qmake (2.01a) Fr. Jul 8 12:16:07 2011
######################################################################

TEMPLATE = lib
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += staticlib
CONFIG += debug_and_release
DESTDIR=../lib
include(../src.pri)

# Input
HEADERS += RandomGenerator.h \
    math_constants.h
SOURCES += RandomGenerator.cpp \
    math_constants.cpp
